In [1]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

In [2]:
tweets_list_MSFT=[]

In [3]:
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#MSFT since:2021-01-01 until:2021-09-21 lang:en').get_items()):
    tweets_list_MSFT.append([tweet.date, tweet.content])

In [5]:
jan_sept = pd.DataFrame(tweets_list_MSFT, columns=['Datetime', 'Text'])
jan_sept.to_csv(r'C:\Users\sowmy\Desktop\jan_sept_MSFT.csv', index=False)

In [1]:
jan_sept

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-390bc4a4c4ee>", line 1, in <module>
    jan_sept
NameError: name 'jan_sept' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2045, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\IPython\core\ultratb.py", line 1170, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "D:\Anaconda\lib\site-packages\IPython\core\ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "D:\Anaconda\lib\site-packages\IPython\core\ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "D:\Anaconda\lib\inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "D:\Anaconda\lib\inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "D:\Anaconda\lib\inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "D:\Anaconda\lib\inspect.py", line 754, in getmodule
    os.path.realpath(f)] = module.__name__
  File "D:\Anaconda\lib\ntpath.py", line 664, in realpath
    if _getfinalpathname(spath) == path:
KeyboardInterrupt

TypeError: object of type 'NoneType' has no len()

In [7]:
tweets_list_AAPL=[]

In [8]:
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#AAPL since:2021-01-01 until:2021-09-21 lang:en').get_items()):
    tweets_list_AAPL.append([tweet.date, tweet.content])

In [9]:
jan_sept_AAPL = pd.DataFrame(tweets_list_AAPL, columns=['Datetime', 'Text'])

In [10]:
jan_sept_AAPL

,Datetime,Text
0,2021-09-20 23:15:03+00:00,"@MacRumors @julipuli Now, if only any of us ou..."
1,2021-09-20 22:15:53+00:00,"Apple Inc price at close, 2021-09-20, is 142.9..."
2,2021-09-20 22:10:27+00:00,AAPL 20210917 Weekly Price Pattern Coordinates...
3,2021-09-20 20:57:29+00:00,#SDC leads today #reddit #wallstreetbets. Stoc...
4,2021-09-20 20:32:57+00:00,Is Apple's stock...\n\n$AAPL #AAPL\n🗞️👉https:/...
...,...,...
13992,2021-01-01 14:57:32+00:00,https://t.co/tHNQwFRqRZ get free stocks for 2...
13993,2021-01-01 12:55:44+00:00,@NiemotkaMike @TraderNickyBAT Gains: #AAPL and...
13994,2021-01-01 06:58:35+00:00,Not all flowers were bloom together. If not #s...
13995,2021-01-01 05:40:03+00:00,Ending this year with small Boom .. #BABA #AAP...
13996,2021-01-01 05:05:52+00:00,"If you #trade #stocks like #FB, #AAPL, #AMZN, ..."

In [12]:
aapl_jan =[]

In [13]:
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#AAPL since:2021-01-01 until:2021-01-31 lang:en').get_items()):
    aapl_jan.append([tweet.date, tweet.content])

In [14]:
jan_AAPL = pd.DataFrame(aapl_jan, columns=['Datetime', 'Text'])

In [15]:
jan_AAPL

,Datetime,Text
0,2021-01-30 23:59:59+00:00,Plz rt\n#WallStreetBets #WSB #NOK #AMC #AAL #A...
1,2021-01-30 23:59:01+00:00,@Gauge_West @vwaptrader1 @valueandtime @WSBCha...
2,2021-01-30 23:58:38+00:00,@honestcurry @DogecoinRise Plz rt\n#WallStreet...
3,2021-01-30 23:58:29+00:00,@DogecoinRise Plz rt\n#WallStreetBets #WSB #NO...
4,2021-01-30 23:58:15+00:00,@DogecoinRise Plz rt\n#WallStreetBets #WSB #NO...
...,...,...
2726,2021-01-01 14:57:32+00:00,https://t.co/tHNQwFRqRZ get free stocks for 2...
2727,2021-01-01 12:55:44+00:00,@NiemotkaMike @TraderNickyBAT Gains: #AAPL and...
2728,2021-01-01 06:58:35+00:00,Not all flowers were bloom together. If not #s...
2729,2021-01-01 05:40:03+00:00,Ending this year with small Boom .. #BABA #AAP...
2730,2021-01-01 05:05:52+00:00,"If you #trade #stocks like #FB, #AAPL, #AMZN, ..."

In [16]:
aapl_feb =[]

In [17]:
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#AAPL since:2021-02-01 until:2021-02-28 lang:en').get_items()):
    aapl_feb.append([tweet.date, tweet.content])

In [18]:
feb_AAPL = pd.DataFrame(aapl_feb, columns=['Datetime', 'Text'])
feb_AAPL

,Datetime,Text
0,2021-02-27 23:02:18+00:00,Warren Buffett praises AAPL stock in annual le...
1,2021-02-27 19:38:02+00:00,"WHERE'S THE ""I-CAR"" ANNOUNCEMENT ??👀👀@Apple #A..."
2,2021-02-27 16:36:23+00:00,oK..had some beers last nite passed out watchi...
3,2021-02-27 15:18:12+00:00,$AAPL seeing an uptick in chatter on /r/wallst...
4,2021-02-27 14:46:33+00:00,#AAPL #AXP Warren Buffett In Annual Letter Sig...
...,...,...
2403,2021-02-01 00:06:37+00:00,@BtcSolidus @craigarot Plz rt\n#WallStreetBets...
2404,2021-02-01 00:06:25+00:00,Plz rt\n#WallStreetBets #WSB #NOK #AMC #AAL #A...
2405,2021-02-01 00:03:25+00:00,@SHARMONJONES @expoundthoughts @craigarot @dog...
2406,2021-02-01 00:03:03+00:00,Plz rt\n#WallStreetBets #WSB #NOK #AMC #AAL #A...
2407,2021-02-01 00:02:38+00:00,@expoundthoughts @craigarot @dogecoin Plz rt\n...

In [19]:
aapl_mar =[]
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#AAPL since:2021-03-01 until:2021-03-31 lang:en').get_items()):
    aapl_mar.append([tweet.date, tweet.content])
    
mar_AAPL = pd.DataFrame(aapl_mar, columns=['Datetime', 'Text'])
mar_AAPL

,Datetime,Text
0,2021-03-30 23:57:59+00:00,#AUDUSD Mid term analysis. Looking Bearish❗️\n...
1,2021-03-30 22:50:46+00:00,Signals could not be any clearer on the 3-min ...
2,2021-03-30 22:34:58+00:00,Apple---&gt; this big whale is waking up - #AA...
3,2021-03-30 22:18:05+00:00,$AAPL #AAPL Anytime price is below a volume sh...
4,2021-03-30 22:13:45+00:00,@KevHatesHipHop I ain’t been this excited abou...
...,...,...
1112,2021-03-01 02:27:38+00:00,@JennyJohnsonHi5 @TedLasso Much deserved 👏🏻👏🏻👏...
1113,2021-03-01 01:43:05+00:00,$AAPL #AAPL Which alert triggers first?\n\nhtt...
1114,2021-03-01 01:01:58+00:00,"@SenseofDollars winners will be #wmt, #cost, #..."
1115,2021-03-01 00:48:01+00:00,Rounding Tops. Bullish or Bearish? - #AAPL cha...
1116,2021-03-01 00:00:12+00:00,"If price breached the pivot, Pump to Dump. MM'..."

In [20]:
msft_jan =[]
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#MSFT since:2021-01-01 until:2021-01-31 lang:en').get_items()):
    msft_jan.append([tweet.date, tweet.content])
    
jan_MSFT = pd.DataFrame(msft_jan, columns=['Datetime', 'Text'])
jan_MSFT

,Datetime,Text
0,2021-01-30 23:21:07+00:00,It is stunning that Steve Jobs and Apple made ...
1,2021-01-30 21:55:14+00:00,How to do some options plays learn here @Marke...
2,2021-01-30 17:15:15+00:00,yungBoul500#7814 #BABA #AAPL #NFLX #MSFT #BYND...
3,2021-01-30 16:36:31+00:00,Waiting for a continuation of the breakout - #...
4,2021-01-30 15:11:23+00:00,More of them #MSFT jobs we keep telling you ab...
...,...,...
1124,2021-01-01 05:40:03+00:00,Ending this year with small Boom .. #BABA #AAP...
1125,2021-01-01 05:05:52+00:00,"If you #trade #stocks like #FB, #AAPL, #AMZN, ..."
1126,2021-01-01 02:20:30+00:00,Financials of #Microsoft #MSFT $MSFT https://t...
1127,2021-01-01 01:22:50+00:00,Did you know that there is a Windows feature t...
1128,2021-01-01 01:17:19+00:00,We are freaking out about this because… among ...

In [23]:
msft_feb =[]
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#MSFT since:2021-02-01 until:2021-02-28 lang:en').get_items()):
    msft_feb.append([tweet.date, tweet.content])
    
feb_MSFT = pd.DataFrame(msft_feb, columns=['Datetime', 'Text'])
feb_MSFT

,Datetime,Text
0,2021-02-27 20:22:00+00:00,@Dynconference making me look even cooler for ...
1,2021-02-27 18:00:02+00:00,I learned today #IDC is actually used for 3 di...
2,2021-02-27 14:58:14+00:00,@MayorBowser @CMCharlesAllen @CM_Silverman @CM...
3,2021-02-27 14:33:24+00:00,@rotanarotana Disrupting n democratizing $300 ...
4,2021-02-27 14:27:59+00:00,@rotanarotana Microsoft has told us all along ...
...,...,...
582,2021-02-01 05:54:20+00:00,#Winklevoss supporting Doge pump and dump is n...
583,2021-02-01 04:48:42+00:00,$MSFT one of the most mentioned on /r/wallstre...
584,2021-02-01 02:26:04+00:00,Trading Ideas: #MSFT Acending triangle Retest?...
585,2021-02-01 02:16:59+00:00,#MSFT Acending triangle Retest? - #MSFT chart ...
586,2021-02-01 00:40:19+00:00,My son practicing Chinese on my wife’s new #su...

In [24]:
msft_mar =[]
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#MSFT since:2021-03-01 until:2021-03-31 lang:en').get_items()):
    msft_mar.append([tweet.date, tweet.content])
    
mar_MSFT = pd.DataFrame(msft_mar, columns=['Datetime', 'Text'])
mar_MSFT

,Datetime,Text
0,2021-03-30 21:28:01+00:00,.@TechRepublic: How to reset a network connect...
1,2021-03-30 20:35:40+00:00,"""Mat how do you unwind when you work a long da..."
2,2021-03-30 20:24:01+00:00,.@Computerworld: Patch Tuesday recap: This mon...
3,2021-03-30 19:45:40+00:00,@Jbuehler777 @RaoulGMI So I would like to buy ...
4,2021-03-30 19:01:29+00:00,Microsoft Ignite wrap-up on Inside Microsoft T...
...,...,...
618,2021-03-01 06:55:23+00:00,great opportunity for everyone!\n#FAANG #AAPL ...
619,2021-03-01 04:26:20+00:00,@JulianAMolinaJ1 If ypu think it was bad that ...
620,2021-03-01 04:16:16+00:00,The InfoStrat blog: Understanding Microsoft Ap...
621,2021-03-01 03:31:53+00:00,#MSFT chart https://t.co/nkGXoIyBb3 via https:...
622,2021-03-01 01:37:47+00:00,"My Watchlist for #Monday March 1, 2021 #GOOGL..."

In [2]:
aapl_jan_sept21 =[]
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#AAPL since:2021-01-01 until:2021-09-21 lang:en').get_items()):
    aapl_jan_sept21.append([tweet.date, tweet.content])
    
jan_sept21_AAPL = pd.DataFrame(aapl_jan_sept21, columns=['Datetime', 'Text'])
jan_sept21_AAPL

,Datetime,Text
0,2021-09-20 23:15:03+00:00,"@MacRumors @julipuli Now, if only any of us ou..."
1,2021-09-20 22:15:53+00:00,"Apple Inc price at close, 2021-09-20, is 142.9..."
2,2021-09-20 22:10:27+00:00,AAPL 20210917 Weekly Price Pattern Coordinates...
3,2021-09-20 20:57:29+00:00,#SDC leads today #reddit #wallstreetbets. Stoc...
4,2021-09-20 20:32:57+00:00,Is Apple's stock...\n\n$AAPL #AAPL\n🗞️👉https:/...
...,...,...
13863,2021-01-01 14:57:32+00:00,https://t.co/tHNQwFRqRZ get free stocks for 2...
13864,2021-01-01 12:55:44+00:00,@NiemotkaMike @TraderNickyBAT Gains: #AAPL and...
13865,2021-01-01 06:58:35+00:00,Not all flowers were bloom together. If not #s...
13866,2021-01-01 05:40:03+00:00,Ending this year with small Boom .. #BABA #AAP...
13867,2021-01-01 05:05:52+00:00,"If you #trade #stocks like #FB, #AAPL, #AMZN, ..."

In [3]:
jan_sept21_AAPL.to_csv(r'C:\Users\sowmy\Desktop\jan_Sept_2021_AAPL.csv', index=False)

In [4]:
amzn_apr_sept21 =[]
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#AMZN since:2021-04-01 until:2021-09-21 lang:en').get_items()):
    amzn_apr_sept21.append([tweet.date, tweet.content])
    
apr_sept21_AMZN = pd.DataFrame(amzn_apr_sept21, columns=['Datetime', 'Text'])
apr_sept21_AMZN

,Datetime,Text
0,2021-09-20 21:32:43+00:00,"#AMZN $AMZN \nSept. 20, 2021 Daily ht..."
1,2021-09-20 21:03:47+00:00,"#AMZN 1H, retraced 0.618 and show typical reve..."
2,2021-09-20 18:37:00+00:00,#AMZN \n\nthis is power of Real #BOXCHART\n\nf...
3,2021-09-20 18:17:18+00:00,Covered Calls Cash Flow Strategy: \n Ticker: $...
4,2021-09-20 18:17:17+00:00,Covered Calls Cash Flow Strategy: \n Ticker: $...
...,...,...
4771,2021-04-01 04:45:33+00:00,$SPY Support and Resistance (Pivots) for Thr 4...
4772,2021-04-01 01:36:40+00:00,#AMZN chart https://t.co/HJlTtcobXp via https:...
4773,2021-04-01 00:34:06+00:00,WATCH RECAP MARCH TRADING WRAP UP STOCKS EQUIT...
4774,2021-04-01 00:23:27+00:00,The Big Five #FAANG Stock and Sector Service i...
4775,2021-04-01 00:06:54+00:00,@MileyCyrus @CashApp $Erickadarling77 and I wo...

In [6]:
apr_sept21_AMZN.to_csv(r'C:\Users\sowmy\Desktop\Apr_Sept_2021_AMZN.csv', index=False)

In [7]:
jpm_apr_sept21 =[]
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#JPM since:2021-04-01 until:2021-09-21 lang:en').get_items()):
    jpm_apr_sept21.append([tweet.date, tweet.content])
    
apr_sept21_JPM = pd.DataFrame(jpm_apr_sept21, columns=['Datetime', 'Text'])
apr_sept21_JPM

,Datetime,Text
0,2021-09-20 19:05:19+00:00,if ever a “time” to enter position within a lo...
1,2021-09-20 18:00:43+00:00,"Happy bday. Still one of my favorite drivers, ..."
2,2021-09-20 17:53:00+00:00,❤️‍🔥❤️‍🔥❤️‍🔥\n\n#JPM #SNDL #NIO #TSLA #GME #AM...
3,2021-09-20 17:22:00+00:00,An interesting interview on #RTO and #WFH but ...
4,2021-09-20 16:39:35+00:00,#StockNews #JPM Opportunity on Hot Stock? JPMo...
...,...,...
793,2021-04-01 11:42:20+00:00,It was a good experience for me and my friends...
794,2021-04-01 08:38:05+00:00,#JPM valued @WeWork at $70B a couple years ago...
795,2021-04-01 07:47:03+00:00,🚀 CRYPTOR GLOBAL - STEALTH TO WEALTH 🇺🇸\n\nCRY...
796,2021-04-01 07:38:29+00:00,In her first cabinet appointments @SuluhuSamia...
797,2021-04-01 04:45:27+00:00,$SPY Support and Resistance (Pivots) for Thr 4...

In [8]:
apr_sept21_JPM.to_csv(r'C:\Users\sowmy\Desktop\Apr_Sept_2021_JPM.csv', index=False)

In [9]:
tsla_apr_sept21 =[]
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#TSLA since:2021-04-01 until:2021-09-21 lang:en').get_items()):
    tsla_apr_sept21.append([tweet.date, tweet.content])
    
apr_sept21_TSLA = pd.DataFrame(tsla_apr_sept21, columns=['Datetime', 'Text'])
apr_sept21_TSLA

,Datetime,Text
0,2021-09-20 23:39:00+00:00,$TSLA one of the most mentioned on wallstreetb...
1,2021-09-20 23:22:28+00:00,Don't be surprised if #TSLA takes the lead in ...
2,2021-09-20 23:13:16+00:00,🚨 There will be a Massive Shift into #Cryptocu...
3,2021-09-20 22:48:06+00:00,Oldie but a goodie.\n\n@elonmusk you could loo...
4,2021-09-20 22:07:13+00:00,@BrianGriffo Couple more shares of #TSLA today...
...,...,...
21895,2021-04-01 00:23:27+00:00,The Big Five #FAANG Stock and Sector Service i...
21896,2021-04-01 00:14:19+00:00,@Ali_Tesla585 I’m going to say that I’ve decid...
21897,2021-04-01 00:10:05+00:00,Tesla (TSLA) could surprise with strong delive...
21898,2021-04-01 00:07:15+00:00,He banged my line i gotta change my number ...
21899,2021-04-01 00:02:27+00:00,It’s so funny how people still think #Tsla is ...

In [10]:
apr_sept21_TSLA.to_csv(r'C:\Users\sowmy\Desktop\Apr_Sept_2021_TSLA.csv', index=False)

In [ ]:
ebay_apr_sept21 =[]
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#EBAY since:2021-01-01 until:2021-09-21 lang:en').get_items()):
    ebay_apr_sept21.append([tweet.date, tweet.content])
    
apr_sept21_ebay = pd.DataFrame(ebay_apr_sept21, columns=['Datetime', 'Text'])
apr_sept21_ebay

Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%23EBAY+since%3A2021-01-01+until%3A2021-09-21+lang%3Aen&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&cursor=scroll%3AthGAVUV0VFVBaAwKuhxZHk-icWgMCshYiZo_wnEnEV-O5uFYCJehgEVVNFUjUBFb4UFQAA&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment: ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out. (read timeout=10)")), retrying

In [ ]:
apr_sept21_pypl.to_csv(r'C:\Users\sowmy\Desktop\Apr_Sept_2021_NFLX.csv', index=False)

In [2]:
msft_jundec =[]
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#MSFT since:2020-06-01 until:2020-12-31 lang:en').get_items()):
    msft_jundec.append([tweet.date, tweet.content])
    
jundec_MSFT = pd.DataFrame(msft_jundec, columns=['Datetime', 'Text'])
jundec_MSFT

,Datetime,Text
0,2020-12-30 22:46:41+00:00,"Alphabet (#GOOG, $GOOG; #GOOGL, $GOOGL), Amazo..."
1,2020-12-30 22:33:05+00:00,$MSFT #MSFT https://t.co/nXIbBmDnue https://t....
2,2020-12-30 21:43:30+00:00,Thanks #BABA #AAPL #NFLX #MSFT #BYND #ROKU htt...
3,2020-12-30 19:01:43+00:00,Thanks 🙏 you #BABA #AAPL #NFLX #MSFT #BYND #RO...
4,2020-12-30 18:34:15+00:00,Thanks #BABA #AAPL #NFLX #MSFT #BYND #ROKU htt...
...,...,...
7850,2020-06-01 10:23:42+00:00,Microsoft 365 &amp; SharePoint PnP Weekly - Ep...
7851,2020-06-01 10:23:42+00:00,Create a list from Microsoft Excel\n\n#SharePo...
7852,2020-06-01 09:39:15+00:00,Wellington Shields Capital Management LLC Sell...
7853,2020-06-01 09:29:04+00:00,$MSFT Microsoft plans to give journalists the ...
7854,2020-06-01 04:16:04+00:00,💯🔛🖥@Microsoft: Microsoft copied new Windows Pa...

In [3]:
jundec_MSFT.to_csv(r'C:\Users\sowmy\Desktop\jundec_MSFT.csv', index=False)